### ISSUE TITLE
azimuth Python package and azimuth web service yield different scores

### ISSUE THREAD

**Issue by dariomel** [MicrosoftResearch/Azimuth#25]
this [script](https://github.com/MicrosoftResearch/Azimuth/files/1644260/bug.zip) reproduces the problem.

Also, the scores obtained by that script from the azimuth Python package seem to agree with those produced by https://crispr.ml when submitting ENSG00000100823 (APEX1), and with those produced by [GPP sgRNA Designer](https://portals.broadinstitute.org/gpp/public/analysis-tools/sgrna-design) when submitting gene ID 328 (also APEX1), indicating that both servers ignore the parameters "Target Cut Length" and "Target Cut %" when calculating the "On-Target Efficacy Score". This limitation is not obvious from the documentation.

**Comment by jjc2718** [comment]
The web service (called by your script) is running an outdated version of the code. See https://github.com/MicrosoftResearch/Azimuth/tree/v1.0 for details on what has changed.

Because of this, we're no longer officially supporting the web service. The results produced by https://crispr.ml and the sgRNA Designer tool are correct (and we recommend using those services going forward), as well as the results produced by the code in the latest version of this repo.
